[package]
name = "bachelor_demo"
version = "0.1.0"
edition = "2021"
description = "Illustrativ demo fra bachelorprosjektet: semi-naiv evaluering, enkel rewriting og cache-skisse."
license = "MIT"

[dependencies]

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
